---
version: '3.6'
services:
  alura-cook-bff-boilerplate:
    build:
      context: .
    image: brendomatos/alura-cook-bff-boilerplate:1.0
    command: python app/server.py
    container_name: alura_cook_boilerplate_bff
    env_file: .local_env
    networks:
      - alura
    ports:
      - "6005:6005"
    volumes:
      - .:/app

networks:
  alura:
    external: true